### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by aliraghebi** [MikeMitterer/dart-validate#6]
Hi @MikeMitterer, Do you have any plans for migrating to null safety?

**Comment by MikeMitterer** [comment]
Hi, no sorry - I don't with work with Dart since one or two years

**Comment by aliraghebi** [comment]
@MikeMitterer Will you accept PR if I do? Or we should fork and publish migrated version as new package?

**Comment by MikeMitterer** [comment]
Please fork. I even delete Dart from my HD :-))

**Comment by aytunch** [comment]
@arsamme are you planning on forking the repo?

**Comment by aliraghebi** [comment]
@aytunch Not yet. I thought this is dependency of FlutterMap but it is not and I don't need in my projects. But I'll fork later in my free time

**Comment by aliraghebi** [comment]
@aytunch There is also a PR for migrating this package #7 but as @MikeMitterer said, He does not do Flutter projects anymore.
@MikeMitterer I can maintain this package if you add me to repo as maintainer.

**Comment by aytunch** [comment]
@arsamme I needed this package for flutter_map to be migrated to nnbd. If it is not a dependency for flutter_map, I am taking it out of the list I was keeping in the related issue in flutter_map. Sorry for the misunderstanding :)

**Comment by aliraghebi** [comment]
@aytunch I could not find this in flutter_map's [pubspec](https://github.com/fleaflet/flutter_map/blob/master/pubspec.yaml)
